meta-networking: fix mbedtls-3.6.3.1 fetch error
Mbed-TLS  moved the v3.6.x line to the 'mbedtls-3.6' branch. Using
branch=main with tag=v${PV} caused BitBake do_fetch to fail with:

```
ERROR: mbedtls-3.6.3.1-r0 do_fetch: Fetcher failure: Unable to find
revision 6fb5120fde4ab889bea402f5ab230c720b0a3b9a in branch main even
from upstream
```

Switch SRC_URI branch from 'main' to 'mbedtls-3.6' for mbedtls 3.6.3.1
recipe.

Signed-off-by: Vince Chang <vince_chang@aspeedtech.com>
Change-Id: If4c59aec18ba7c6122cbd3c44be0d24a27c1cf3e